addSbtPlugin("org.playframework" % "sbt-plugin"   % "3.1.0-M9")
addSbtPlugin("com.github.sbt"    % "sbt-digest"   % "2.2.0-M1")
addSbtPlugin("com.github.sbt"    % "sbt-gzip"     % "2.1.0-M1")
addSbtPlugin("com.github.sbt"    % "sbt-stylus"   % "2.1.0-M1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.6.1")
