name: Check

on:
  pull_request:

  push:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  check-code-style:
#    name: Code Style
#    uses: playframework/.github/.github/workflows/cmd.yml@v3
#    with:
#      cmd: sbt validateCode

#  check-binary-compatibility:
#    name: Binary Compatibility
#    uses: playframework/.github/.github/workflows/binary-check.yml@v3

  check-docs:
    name: Docs
    uses: playframework/.github/.github/workflows/cmd.yml@v3
    with:
      cmd: sbt doc

  tests:
    name: Tests
    needs:
#      - "check-code-style"
#      - "check-binary-compatibility"
      - "check-docs"
    uses: playframework/.github/.github/workflows/cmd.yml@v3
    with:
      java: 17, 11
      scala: 2.13.x
      cmd: |
        # Clone generated docs so that we can run some integration tests
        git clone -o origin https://github.com/playframework/play-generated-docs.git $PWD/data/generated
        sbt ++$MATRIX_SCALA test

  test_scala_3:
    needs:
      - "check-docs"
    uses: playframework/.github/.github/workflows/cmd.yml@v3
    with:
      java: 17
      cmd: |
        git clone -o origin https://github.com/playframework/play-generated-docs.git $PWD/data/generated
        sbt "++ 3.x" compile # TODO fix test

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v3
